# this workflow job is used to automate provision resources 
# on Google Cloud with terraform
# author: Marek Chmielowski (based on simple example by Yann Mulonda)

name: 'Terraform CI'
run-name: Deploy by @${{ github.actor }}

on:
  push:
    branches:
    - main
    - terraform
    - develop
    paths-ignore:
      - README.md
      - CHANGELOG.md # Should never be edited anyway
      - .gitignore
      - .github/**
  pull_request:
    branches:
      - master
      - terraform
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    name: 'Provision GCP'
    runs-on: ubuntu-latest
    # environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    # # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      # this is the json key of the service account created on the project
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init
      # this is the json key of the service account created on the project
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color -input=false
      continue-on-error: true
      # this is the json key of the service account created on the project
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        
      # On push to terraform branch, build or change infrastructure according to Terraform configuration files
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    - name: Apply only on push to main
      if: github.ref != 'refs/heads/main' || github.event_name != 'push'
      run: exit 1
      
    - name: Terraform Plan Failed
      if: steps.plan.outcome == 'failure'
      run: exit 1
        
    # Apply infrastructure changes
    - name: Terraform Apply
      # If any commit message in your push or the HEAD commit of your PR 
      # contains the strings [Apply_Changes] -- then terraform Apply step will run
      # if: github.ref == 'refs/heads/main' && github.event_name == 'push' && "contains(github.event.commits[0].message, '[Apply_Changes]')"
      if: "github.event_name == 'push' && contains(github.event.commits[0].message, '[Apply_Changes]')"
      run: echo "Deploying to GCP"; terraform apply -auto-approve
      # this is the json key of the service account created on the project
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
     
    - name: Terraform Destroy
      # If any commit message in your push or the HEAD commit of your PR 
      # contains the strings [Destroy_All] -- then terraform Destroy step will run
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push' && "contains(github.event.commits[0].message, '[Destroy_All]')"
      if: "github.event_name == 'push' && contains(github.event.commits[0].message, '[Destroy_All]')"
      run: terraform apply -destroy -auto-approve
      # this is the json key of the service account created on the project
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
